config/routes.rb
class PageConstraints
  def matches?(request)
    !request.path.start_with?('/admin/auth')
  end
end

Rails.application.routes.draw do

  devise_for :admin, Slices::Config.devise_for_options

  namespace :admin do
    get 'site_maps' => 'site_maps#index', as: :root # Devise redirects here after sign in
    get 'site_maps' => 'site_maps#index'
    put 'site_maps/update' => 'site_maps#update'
    get 'pages/search' => 'page_search#show'
    resources :pages, :except => [:index, :edit] do
      resources :entries, :only => [:index]
    end
    resources :assets, :except => [:show]
    resources :snippets
    resources :admins
  end
  get '/admin' => redirect('/admin/site_maps')

  get 'slices/templates(/:slice)/:name.:format' => 'static_assets#templates'
  get ':action/:asset_type(/:folder)/*name.:format' => 'static_assets',
    :constraints => {
    :asset_type => /(stylesheets|javascripts|images)/,
    :action => /(slices|sites)/
  }, :as => :static_assets

  get ':status.html' => 'pages#virtual_error_pages'
  post '*path' => 'pages#create'
  get '*path' => 'pages#show', as: :page, :constraints => PageConstraints.new

  root to: 'pages#show'
end

app/views/admin/pages/_breadcrumbs.html.erb
<div class="navigation">
  <ul id="breadcrumbs">
    <li>
      <%= link_to 'Sitemap', admin_site_maps_path %>
    </li>

    <% @page.breadcrumbs.reverse_each do |page| %>
      <li class="<%= 'current' if page == @page.source %>">
        <% if page.set_page? %>
          <%= link_to page.name, admin_page_entries_path(page) %>
        <% else %>
          <%= link_to page.name, admin_page_path(page) %>
        <% end %>
      </li>
    <% end %>

    <li>
      <select id="children">
        <option selected disabled>Children of this page…</option>
        <% @page.children.each do |page| %>
          <% if page.set_page? %>
            <option value="<%= admin_page_entries_path page %>"><%= page.name %></option>
          <% else %>
            <option value="<%= admin_page_path page %>"><%= page.name %></option>
          <% end %>
        <% end %>
        <option disabled role="separator">---</option>
        <option value="<%= new_admin_page_path parent_id: @page.bson_id %>">Add Child…</option>
      </select>
    </li>
  </ul>
</div>

app/views/admin/pages/_fields.html.erb
<%= form.cms_select :layout, @layouts %>

app/views/admin/pages/_slices.html.erb
$(function() {

  slices.controller.init(
    '<%= @page.bson_id %>',
    {
      availableSlices: <%= raw Slices::AvailableSlices.all.to_json %>,
      availableContainers: <%= raw @layout.containers.to_json %>,

      mainTemplate: '<%= @page.main_template %>',
      metaTemplate: '<%= @page.meta_template %>',

      mainExtraTemplates: <%= raw @page.main_extra_templates.to_json %>,
      metaExtraTemplates: <%= raw @page.meta_extra_templates.to_json %>,

      super_user: <%= current_admin.super_user? %>,
      i18n: <%= Slices::Config.i18n? %>,

      loadPagePath: '/admin/pages/{{id}}.json?locale=<%= I18n.locale %>',
      savePagePath: '/admin/pages/{{id}}.json?locale=<%= I18n.locale %>',

      <% if @page.editing_entry_content_slices?(params[:entries]) %>
        mainTemplate: 'set_page_entry_content_main',
        metaTemplate: 'set_page_entry_content_meta',
        loadPagePath: '/admin/pages/{{id}}?locale=<%= I18n.locale %>&entries=1',
        savePagePath: '/admin/pages/{{id}}?locale=<%= I18n.locale %>&entries=1'
      <% end %>
    }
  );

});

app/views/admin/pages/new.html.erb
<%= form_for [:admin, @page],
  builder: Slices::CmsFormBuilder do |form| %>
  <ul class="fields">
    <%= form.hidden_field :parent_id %>
    <% if params.has_key?(:type) %>
      <%= hidden_field_tag :type, params[:type] %>
    <% end %>
    <%= form.cms_text_field :name, required: false %>

    <%= render(
      partial: Slices::Config.page_fields_template,
      locals: { form: form }
    ) %>
  </ul>
  <div class="bottom-toolbar">
    <%= form.submit value: "Create Page" %>
  </div>
<% end %>

app/views/admin/pages/show.html.erb
<form id="slices-form">
  <div id="container-actions">
    <% if Slices::Config.i18n? %>
      <div class="toolbar translations">
        <nav>
          Edit in
          <ul>
            <% I18n.available_locales.each do |locale| %>
              <li>
                <%= link_to_if locale != I18n.locale, t("locales.#{locale}", default: locale.to_s), admin_page_path(@page.source, locale: locale) %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    <% end %>
    <div class="toolbar">
      <nav>
        <ul>
          <li class="back"><%= link_to "Cancel editing (lose unsaved changes)", admin_site_maps_path %></li>
        </ul>
      </nav>
      <div class="actions">
        <ul>
          <li><a id="minimise" class="button">Minimise all slices</a></li>
          <li>
            <%= link_to_view_page(@page.source, id: 'page-view-on-site', target: 'site', class: 'button standard') %>
          </li>
          <li><input type="submit" value="Save changes" id="save-changes" disabled></li>
        </ul>
      </div>
    </div>
  </div>

  <div id="main">
    <%= render("breadcrumbs") unless @page.set_page? %>

    <section>
      <div id="page-meta-fields">
        <ul id="page-main"></ul>
        <ul id="page-meta"></ul>
        <ul id="page-extra-main"></ul>
      </div>

      <h1>Content Slices</h1>

      <div id="container-slices">
        <ul id="container-tab-controls"></ul>

        <div id="containers-holder"></div>

        <!-- cloned via JS and then removed once it has been added! -->
        <div id="add-slice-fields" class="boxy add-slice-fields">
          <select id="add-slice-option">
            <option selected disabled>Add a slice</option>
          </select>
        </div>
      </div>
    </section>
  </div>
</form>

<% content_for :js_head do %>
  <%= render "slices" %>
  slices.trigger('pages:show');
<% end %>