config/routes.rb
class PageConstraints
  def matches?(request)
    !request.path.start_with?('/admin/auth')
  end
end

Rails.application.routes.draw do

  devise_for :admin, Slices::Config.devise_for_options

  namespace :admin do
    get 'site_maps' => 'site_maps#index', as: :root # Devise redirects here after sign in
    get 'site_maps' => 'site_maps#index'
    put 'site_maps/update' => 'site_maps#update'
    get 'pages/search' => 'page_search#show'
    resources :pages, :except => [:index, :edit] do
      resources :entries, :only => [:index]
    end
    resources :assets, :except => [:show]
    resources :snippets
    resources :admins
  end
  get '/admin' => redirect('/admin/site_maps')

  get 'slices/templates(/:slice)/:name.:format' => 'static_assets#templates'
  get ':action/:asset_type(/:folder)/*name.:format' => 'static_assets',
    :constraints => {
    :asset_type => /(stylesheets|javascripts|images)/,
    :action => /(slices|sites)/
  }, :as => :static_assets

  get ':status.html' => 'pages#virtual_error_pages'
  post '*path' => 'pages#create'
  get '*path' => 'pages#show', as: :page, :constraints => PageConstraints.new

  root to: 'pages#show'
end

app/views/admin/shared/_asset_storage.html.erb
<script>
  <% if Slices::Config.s3_storage? %>
    slices.S3_UPLOADER_DEFAULTS = {
      AWSAccessKeyId        : '<%= Slices::Config.s3_credentials[:access_key_id] %>',
      acl                   : 'public-read',
      policy                : '<%= policy %>',
      signature             : '<%= signature %>',
      success_action_status : '201',
    };

    slices.S3_URL = 'https://<%= Slices::Config.s3_credentials[:bucket] %>.s3.amazonaws.com/';
    slices.S3_TEMPFILE_KEY_PREFIX = '<%= Slices::Config::S3_TEMPFILE_KEY_PREFIX %>';
    slices.fileClass = slices.S3File;
  <% else %>
    slices.fileClass = slices.File;
  <% end %>
</script>

app/views/admin/shared/_custom_links.html.erb
<li><%= link_to 'Suggestion Box', 'https://github.com/withassociates/slices/issues' %></li>

app/views/admin/shared/_custom_navigation.html.erb
<%= admin_nav_link 'Source', 'https://github.com/withassociates/slices' %>

app/views/admin/shared/_navigation.html.erb
<%= admin_nav_link("Sitemap", admin_site_maps_path) %>
<%= admin_nav_link("Assets", admin_assets_path) %>
<%= admin_nav_link("Snippets", admin_snippets_path) if Slices::Config.snippets? %>
<%= admin_nav_link("Administrators", admin_admins_path) %>
<%= render_custom_navigation %>