config/routes.rb
class PageConstraints
  def matches?(request)
    !request.path.start_with?('/admin/auth')
  end
end

Rails.application.routes.draw do

  devise_for :admin, Slices::Config.devise_for_options

  namespace :admin do
    get 'site_maps' => 'site_maps#index', as: :root # Devise redirects here after sign in
    get 'site_maps' => 'site_maps#index'
    put 'site_maps/update' => 'site_maps#update'
    get 'pages/search' => 'page_search#show'
    resources :pages, :except => [:index, :edit] do
      resources :entries, :only => [:index]
    end
    resources :assets, :except => [:show]
    resources :snippets
    resources :admins
  end
  get '/admin' => redirect('/admin/site_maps')

  get 'slices/templates(/:slice)/:name.:format' => 'static_assets#templates'
  get ':action/:asset_type(/:folder)/*name.:format' => 'static_assets',
    :constraints => {
    :asset_type => /(stylesheets|javascripts|images)/,
    :action => /(slices|sites)/
  }, :as => :static_assets

  get ':status.html' => 'pages#virtual_error_pages'
  post '*path' => 'pages#create'
  get '*path' => 'pages#show', as: :page, :constraints => PageConstraints.new

  root to: 'pages#show'
end

app/models/layout.rb
class Layout
  def self.all
    files.map do |layout|
      layout = layout.split('/').last.gsub(file_extension, '')
      [layout.titleize, layout]
    end
  end

  def self.files
    files = []
    SlicesController.view_paths.each do |resolver|
      query = File.join(resolver, 'layouts', "*#{file_extension}")
      files.concat(Dir.glob(query))
    end
    files.reject do |file|
      file.include?('admin.html.erb')
    end.uniq.sort
  end

  def self.file_extension
    '.html.erb'
  end

  def initialize(name)
    @name = name
  end

  def path
    self.class.files.select do |path|
      path.split('/').last == @name + self.class.file_extension
    end.first
  end

  def containers
    parser = Slices::ContainerParser.new(path)
    parser.parse
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <%= csrf_meta_tag %>
  <title><%= cms_title %></title>

  <%= stylesheet_link_tag 'slices/slices' %>
  <%= javascript_include_tag 'slices/slices' %>
  <%= render "admin/shared/asset_storage" %>

  <meta name="robots" content="noindex, nofollow">
  <script type="text/javascript">
    $(function() {
      <%= yield :js_head %>
    });
  </script>
</head>
<body class="<%= body_class_from_controller %>">
  <div class="jqmWindow modal" id="general-modal"></div>
  <div id="server-communication">Loading...</div>

  <div id="container">
    <header id="layout">
      <% if admin_signed_in? -%>
        <ul>
          <li><%= current_admin.email %></li>
          <%= render_custom_links %>
          <li><%= link_to "View Site", root_path, target: "_blank" %></li>
          <li><%= link_to "Account", admin_admin_path(current_admin) %></li>
          <li><%= link_to "Log out", destroy_admin_session_path %></li>
        </ul>
      <% end -%>
      <nav>
        <ul>
          <% if admin_signed_in? -%>
            <%= render('admin/shared/navigation')  %>
          <% else -%>
            <li>&nbsp;</li>
          <% end -%>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </div>

  <script type="text/html" id="livefield-result-template">
    <li data-value="{{path}}">
      <span class="name">{{name}}</span>
      <span class="path">{{path}}</span>
    </li>
  </script>
</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page.name %></title>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    <%= yield :js_head %>
  </script>
</head>
<body class="default">
  <%= edit_in_cms %>
  <header>
    <nav>
      <%= primary_navigation %>
      <%= secondary_navigation(depth: 10) %>
    </nav>
  </header>
  <article class="container_one">
    <%= container "container_one", primary: true %>
  </article>
  <aside class="container_two">
    <%= container "container_two" %>
  </aside>
</body>
</html>